index:
    path: /
    controller: App\Controller\DefaultController::index

main:
    path: /main
    controller: App\Controller\MainController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    methods: GET

stocks:
    path: /admin/stocks
    controller: App\Controller\StocksController::index

add_stock:
    path: /admin/stocks/add/{id}
    controller: App\Controller\AddStockController::index
    requirements:
        id: "[^/]+"

manage_book_stock:
    path: /admin/manage/book/stock/{id}
    controller: App\Controller\ManageBookStockController::index
    requirements:
        id: "[^/]+"

read_employees:
    path: /admin/employees/read
    controller: App\Controller\ReadEmployeesController::index

add_employee:
    path: /admin/employees/add
    controller: App\Controller\AddEmployeeController::index

update_employee:
    path: /admin/employees/update/{id}
    controller: App\Controller\UpdateEmployeeController::index
    requirements:
        id: "[^/]+"

update_customer:
    path: /admin/customer/update/{id}
    controller: App\Controller\UpdateCustomerController::index
    requirements:
        id: "[^/]+"

read_subscription:
    path: /admin/subscription/read
    controller: App\Controller\ReadSubscriptionsController::index

add_subscription:
    path: /admin/subscription/add
    controller: App\Controller\AddSubscriptionController::index

update_subscription:
    path: /admin/subscription/update/{id}
    controller: App\Controller\UpdateSubscriptionController::index
    requirements:
        id: "[^/]+"

add_subscription_to_customer:
    path: /admin/subscription/add/customer/{id}
    controller: App\Controller\AddSubscriptionToCustomer::index
    requirements:
        id: "[^/]+"

read_borrow:
    path: /admin/borrow/read
    controller: App\Controller\ReadBorrowController::index

add_borrow:
    path: /admin/borrow/add
    controller: App\Controller\AddBorrowController::index

delete_borrow:
    path: /admin/borrow/delete/{id}
    controller: App\Controller\DeleteBorrowController::index
    requirements:
        id: "[^/]+"
